version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: beanauction_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: beanauction_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
